### ISSUE TITLE
Native Not Found.

### ISSUE THREAD

**Issue by SyntX34** [srcdslab/sm-plugin-TogsJumpStats#4]
Exception reported: Native is not bound
L 03/23/2023 - 20:02:00: [SM] Blaming: TogsJumpStats.smx
L 03/23/2023 - 20:02:00: [SM] Call stack trace:
L 03/23/2023 - 20:02:00: [SM]   [0] SBPP_CheckerGetClientsBans
L 03/23/2023 - 20:02:00: [SM]   [1] Line 621, TogsJumpStats.sp::Discord_Notify
L 03/23/2023 - 20:02:00: [SM]   [2] Line 603, TogsJumpStats.sp::Forward_OnDetected
L 03/23/2023 - 20:02:00: [SM]   [3] Line 581, TogsJumpStats.sp::NotifyAdmins
L 03/23/2023 - 20:02:00: [SM]   [4] Line 441, TogsJumpStats.sp::Event_PlayerJump

Line 621 : Discord_Notify(client, reason, sStats);

It was  working fine till yesterday but i dont know how this issue came all of sudden. I did not changed anything in code. i just set up webhook. Please tell me solutions to fix this issue... i checked all plugins, other are working fine which are using  DiscordWebhookAPI.

**Comment by Rushaway** [comment]
Upgrade your Sourcebans plugin.
These change was introduced in https://github.com/sbpp/sourcebans-pp/commit/fbaf46e3f235fa5fa91fa4cc8cfb7720c31b3e6f and renamed in https://github.com/sbpp/sourcebans-pp/commit/a7476e60bbd100c50c086750b278b27999a0f8bd

**Comment by SyntX34** [comment]
**Fixed.**
